name: release on push
on:
    push: # build anytime there is a push to main
        branches:
        - main
    workflow_dispatch:
    
    schedule:
        - cron: "*/30 8-20 * * 1-5"
          
jobs:
    content-release:
        uses: department-of-veterans-affairs/next-build/.github/workflows/projects/next-build/.github/workflows/content-release.yml@main
        with:
            build_type: "PROD"
            runs-on: ubuntu-latest
        